version: '3.8'
services:
  server:
    image: "amyangxyz111/awesome-connect:latest"
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - awesome-network
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - awesome-network

volumes:
  caddy_data:
  caddy_config:


networks:
  awesome-network:
    driver: bridge
